[settings]
timeout = 1000

[relaychain]
chain = "paseo-local"
chain_spec_command = "./bin/runtimes/paseo/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
default_args = ["-lparachain=debug", "-lxcm=trace"]
default_command = "./bin/polkadot"
scheduling_lookahead = 2

[relaychain.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2

[[relaychain.nodes]]
extra_args = [
  "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all",
]
name = "alice"
validator = true
rpc_port = 10000

[[relaychain.nodes]]
extra_args = [
  "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all",
]
name = "bob"
validator = true

[[relaychain.nodes]]
extra_args = [
  "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all",
]
name = "charlie"
validator = true

[[relaychain.nodes]]
extra_args = [
  "--force-authoring -lparachain=debug --unsafe-rpc-external --rpc-cors=all",
]
name = "dave"
validator = true

[[parachains]]
id = 2281
chain = "local"
chain_spec_command = "./target/release/chain-spec-generator {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true
add_to_genesis = true
onboard_as_parachain = true

[[parachains.collators]]
command = "./bin/polkadot-parachain"
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
name = "kreivo1"
rpc_port = 20000

[[parachains.collators]]
command = "./bin/polkadot-parachain"
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
name = "kreivo2"
rpc_port = 21000

[[parachains.collators]]
command = "./bin/polkadot-parachain"
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
name = "kreivo3"
rpc_port = 22000

[[parachains.collators]]
command = "./bin/polkadot-parachain"
args = ["--force-authoring --log=xcm=trace,parachain=trace"]
name = "kreivo4"
rpc_port = 23000
