name: Short benchmarks (frame-omni-bencher)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUNTIME_NAME: kreivo_runtime.compact.compressed.wasm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ubuntu dependencies
        shell: bash
        run: sudo apt update && sudo apt install -y protobuf-compiler

      - name: Use Stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rust-src

      - uses: actions/checkout@v4

      - name: Release build with `runtime-benchmarks`
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile production --features ${{ github.ref_name == 'dev' && 'paseo,runtime-benchmarks' || 'runtime-benchmarks' }} --locked -p kreivo-runtime

      - name: Upload runtime to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_number }}-runtime
          path: ./target/production/wbuild/kreivo-runtime/${{ env.RUNTIME_NAME }}

  quick-benchmarks-omni:
    needs: build
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C debug-assertions"
      RUST_BACKTRACE: "full"
      WASM_BUILD_NO_COLOR: 1
      WASM_BUILD_RUSTFLAGS: "-C debug-assertions"
      RUST_LOG: "frame_omni_bencher=info"
    timeout-minutes: 30
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.run_number }}-runtime

      - name: Install CLI
        run: |
          cargo install frame-omni-bencher --profile=production --locked

      - name: script
        id: required
        run: |
          frame-omni-bencher v1 benchmark pallet --runtime ${{ env.RUNTIME_NAME }} --all --steps 2 --repeat 1 --quiet
