name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NIGHTLY_VERSION: 'nightly'
  EXTRA_ARGS: ''

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: pandres95/kreivo-ci
    steps:
      - uses: actions/checkout@v4

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
          key: check

      - name: Check Build
        uses: actions-rs/cargo@v1
        with:
          command: check
          toolchain: ${{ env.NIGHTLY_VERSION }}
          args: --release --locked --all-features --workspace ${{ env.EXTRA_ARGS }}

  clippy:
    runs-on: ubuntu-latest
    container:
      image: pandres95/kreivo-ci
    permissions:
      checks: write
    env:
      SKIP_WASM_BUILD: 1
    steps:
      - uses: actions/checkout@v4

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
          key: check

      - name: Annotate with Clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: ${{ env.NIGHTLY_VERSION }}
          args: --release --locked --all-features --workspace ${{ env.EXTRA_ARGS }}

  test:
    runs-on: ubuntu-latest
    container:
      image: pandres95/kreivo-ci
    env:
      SKIP_WASM_BUILD: 1
    steps:
      - uses: actions/checkout@v4

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          cache-all-crates: true
          key: test

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: ${{ env.NIGHTLY_VERSION }}
          args: --lib --locked --all-features --workspace ${{ env.EXTRA_ARGS }}
